### PR TITLE
Replace removed API with new equivalents

### PR DESCRIPTION
**Pull request by LordBoos**
Found your PR to HA Core and decided to try it as a custom_component because current official integration stopped working. While testing, I've noticed that the integration was still not working for me, even after creating new OAuth token.
I had to replace deprecated (now removed) APIs with new ones and add new OAuth scope required for one of the new APIs.
With these changes, the integration works perfectly for me.

### CODE REVIEW

**Comment by joostlek** [comment]
The big problem I am currently facing is that everything has to go step by step. I can't rework a complete integration in one PR.

It's a bug currently. Yes. We could update the current code to use that new endpoint, but that also leads to everyone having to renew their token as their old one doesn't have the required scope.

So my preference is to get the initial reviews done to actually only have one breaking change in total. Since after this change everyone has to add twitch again.

Best case scenario, this fix would be in in 2023.10. The config flow is the hardest part, if that's done this fix will be ezpz

**Comment by LordBoos** [comment]
Thing is that the old APIs were probably removed, because they are not working for me at all.

I know that forcing everyone to renew token is bad, but isn't it better than having completely non-functional integration? 

From my testing, everything is working pretty good with those changes. I just removed Twitch from configuration.yaml, added this as custom-component and did config-flow setup in HA integrations without any issues.

**Comment by joostlek** [comment]
There are only 170 people using twitch, so atm it's not the top of my priority list. Can we maybe agree on, if I don't get the config flow in 2023.10 we integrate the new methods and make it a breaking change?

**Comment by LordBoos** [comment]
Ok, no problem for me. I'll be using it as a custom_component in the meantime.

**Pull request closed without merging**
